### ISSUE TITLE
5v to 10-18v voltage raising power supply

### ISSUE THREAD

**Issue by rusefillc** [rusefi/stim#1]
Can we take +5v from USB and make somewhere from 10 to 18 volts out of it? this would eliminate need of wall power supply and increase overall usability

**Comment by mck1117** [comment]
There's a catch I didn't think of - if we want to actually test injector drivers with 1-2 amps, this won't work.

**Comment by rusefillc** [comment]
would we need 1a to validate soldering on low side drivers?
