### ISSUE TITLE
digital inputs: CAN transiever

### ISSUE THREAD

**Issue by rusefillc** [rusefi/stim#13]
CAN bus could be useful

PA11 (CAN1_RX) and PA12 (CAN1_TX)

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/193623460-b6c27aea-91d5-401f-823e-550f9def9d4c.png)

**Comment by rusefillc** [comment]
не понимаю, откуда берутся 3.3

давай нарисуем линию к источнику 3.3?

**Comment by Qwerty-OFF** [comment]
Поправил
![image](https://user-images.githubusercontent.com/4116383/193626186-1e3f16ee-28b8-4c48-8d54-ec940cb51678.png)
