### ISSUE TITLE
60+34 pin superseal 1.0 connectors

### ISSUE THREAD

**Issue by rusefillc** [rusefi/stim#14]
let's use 60+34 pin superseal 1.0 connector same as https://github.com/rusefi/alphax-8chan/

Power, CAN and all inputs should be moved to that connectors, current wire provisions are not needed

back side of PCB should have some nice silk please

**Comment by Nadezhda-n** [comment]
What are the inputs here? :)

**Comment by rusefillc** [comment]
Sorry outputs @Nadezhda-n

**Comment by Nadezhda-n** [comment]
> Sorry outputs @Nadezhda-n

![image](https://user-images.githubusercontent.com/99179773/235671317-93591d5a-6cc3-4ab0-a756-d4be14d3a241.png)
?

**Comment by Nadezhda-n** [comment]
Плату нужно увеличивать, верно?
![image](https://user-images.githubusercontent.com/99179773/235672479-a9105463-2cae-4792-8a37-fea13b4919f6.png)

**Comment by rusefillc** [comment]
@rusefillc не совсем - ведь на эти 60 пинов уйдут примерно 42 текущих отверстий справа

48 каналов мне по факту просто не нужно:

1-40 идут на разъём. 
оставшиеся 8 идёт на дырочки в середине платы

**Comment by rusefillc** [comment]
т.е. правый-верхний угол платы заменяется вот на такую распиновку

https://rusefi.com/docs/pinouts/stim/

https://github.com/rusefi/stim/blob/main/digital_inputs/connectors/60pins.yaml

**Comment by Nadezhda-n** [comment]
![image](https://github.com/rusefi/stim/assets/99179773/d59cfc3f-a61a-4210-b172-c263fb708de0)

**Comment by Nadezhda-n** [comment]
Куда подключать out4-out7??
![image](https://github.com/rusefi/stim/assets/99179773/8a51bc0f-f887-47ef-a24a-7f46190bb285)

**Comment by Nadezhda-n** [comment]
![image](https://github.com/rusefi/stim/assets/99179773/eaf04535-6a52-44d0-a6fb-826308c292be)
Такая будет компоновка? 
@rusefillc

**Comment by rusefillc** [comment]
если 60 пин развернуть на 180 градусов - то да.

**Comment by rusefillc** [comment]
> Куда подключать out4-out7??

 out4-out7 это внутренние трассы, идущие на чипы - их не нужно трогать и выводить на разъёмы

**Comment by Nadezhda-n** [comment]
Я плату добавила, вроде с меня на данном этапе все.
@rusefillc @Qwerty-OFF

**Comment by Qwerty-OFF** [comment]
Подразумевалось что-то типа OUT_HALL0, OUT_HALL1, сейчас названия выглядят немного странно
![image](https://github.com/rusefi/stim/assets/4116383/a09aa2a3-0876-4106-be1a-8be534387ade)

@rusefillc для CAN 120 Ом и защитные диоды нужны?

@rusefillc хочешь ли ты подписи функционала у разъемов с обратной стороны платы или это особый вид наказания специально для меня?

Больше возражений не имею

**Comment by rusefillc** [comment]
@Qwerty-OFF спасибо огромное! два тикета сделал
