### ISSUE TITLE
let's have china solder CN1-2

### ISSUE THREAD

**Issue by rusefillc** [rusefi/stim#18]
let's add part numbers for "x by 2" headers for JLC to solder so that I can just hook nucleo board to stim board

![image](https://github.com/rusefi/stim/assets/48498823/35af8079-edd8-4bf7-bc31-13deaf12fff7)

![image](https://github.com/rusefi/stim/assets/48498823/13a91d9d-66fb-4950-b123-3ad93d1786de)

**Comment by rusefillc** [comment]
если у JLC нет идеальных разъёмов - давайте обсудим, насколько будет просто запаять хотя бы частичный разъём - может быть скобинировать из нескольких разъёмов с пропусками

сейчас добавлю картинку, чтоб повысить шанс меня понять

**Comment by rusefillc** [comment]
![16908185576371278729245498407034](https://github.com/rusefi/stim/assets/48498823/03c16412-c00e-4d34-b639-a77c7091a54d)

**Comment by Nadezhda-n** [comment]
Я не знаю, кто такие "x by 2" headers

**Comment by rusefillc** [comment]
> Я не знаю, кто такие "x by 2" headers

я про разъёмы на U11, там 6 штук разного размера например 8x2 и 10x2 и ещё какие-то более длинные

**Comment by Nadezhda-n** [comment]
> > Я не знаю, кто такие "x by 2" headers
> 
> я про разъёмы на U11, там 6 штук разного размера например 8x2 и 10x2 и ещё какие-то более длинные

Вместо U11 стоят разъемы 2,54 стандартные и нужно подобрать перечень с jls, чтобы поставиьь их во все отверстия футпринта?

**Comment by rusefillc** [comment]
@Nadezhda-n на 90% да!

если всё легко и у них есть все разъёмы - то просто ставим

нюансы
* если какой-то разъём у нас не испольщуется вообще - аргумент не ставить, чтоб проще было вставлять-вынимать U11
* если правильных огромных у JLC нет, то большую серцию есть идея разделить логически и попросить JLC напаять хотя бы самые важные для нас сектора

**Comment by Nadezhda-n** [comment]
> @Nadezhda-n на 90% да!
> 
> если всё легко и у них есть все разъёмы - то просто ставим
> 
> нюансы
> 
> * если какой-то разъём у нас не испольщуется вообще - аргумент не ставить, чтоб проще было вставлять-вынимать U11
> * если правильных огромных у JLC нет, то большую серцию есть идея разделить логически и попросить JLC напаять хотя бы самые важные для нас сектора

![image](https://github.com/rusefi/stim/assets/99179773/e915a52e-28a2-4ff4-b31a-35d82f7480ff)

Условно, если в линии у нас используется  только эти 3 пина, то есть можно взять PLD-10 или нужно побольше? (Кстати, вилки нужны?)

**Comment by Nadezhda-n** [comment]
![image](https://github.com/rusefi/stim/assets/99179773/260440e1-1d5f-4e1e-94bf-86e6ad9922ac)
C92264 DS1023-2x17SF11
C92264 DS1023-2x17SF11

C92267 DS1023-2x8SF11
C132129 DS1023-2x15SF11

C92266 DS1023-2x10SF11
C92264 DS1023-2x17SF11

C92266 DS1023-2x10SF11
C92266 DS1023-2x10SF11
C132127 DS1023-2x13SF11

**Comment by Qwerty-OFF** [comment]
![image](https://github.com/rusefi/stim/assets/4116383/3b59084b-7f68-414e-bd71-3d6e0f54ee94)

**Comment by Nadezhda-n** [comment]
> @Qwerty-OFF 

![image](https://github.com/rusefi/stim/assets/99179773/d44fe98e-0990-483e-b645-e072c2b90d34)

Суть в том, что корпус разъема немного больше (0,5+-0,3мм), и вот вплотную три подряд разъема могут не влезть, поэтому может все таки сделаем с зазорами, как я кидала выше?

Или ты используешь другие разъемы?

**Comment by Qwerty-OFF** [comment]
Соседние разъемы не будут паяться, я в BOM поставил только те, что нужны
