### ISSUE TITLE
CAN на большой разъём

### ISSUE THREAD

**Issue by rusefillc** [rusefi/stim#19]
https://rusefi.com/docs/pinouts/stim/?connector=main&pin=23B
https://rusefi.com/docs/pinouts/stim/?connector=main&pin=24B

**Comment by Nadezhda-n** [comment]
![image](https://github.com/rusefi/stim/assets/99179773/a8adaffc-8809-4608-a872-4b86d19730e0)
уже

**Comment by rusefillc** [comment]
Был слеп
