### ISSUE TITLE
шёлкография разъёмов сзади

### ISSUE THREAD

**Issue by rusefillc** [rusefi/stim#23]

**Comment by Nadezhda-n** [comment]
![image](https://github.com/rusefi/stim/assets/99179773/0be77ec2-2369-4b8b-b557-ce5ac008dbfa)
так подойдет?
![image](https://github.com/rusefi/stim/assets/99179773/a5a17575-8d9e-4677-8a58-9553605fbe19)
Чтобы путаницы с номерами не было, эти пины начинала с буквы Т, REF записала числовыми значениями, HALL как OUT_D0-7
@Qwerty-OFF

**Comment by rusefillc** [comment]
@Nadezhda-n красота!
