### ISSUE TITLE
названия пинов потерялись

### ISSUE THREAD

**Issue by rusefillc** [rusefi/stim#28]
было удобнее

![image](https://github.com/rusefi/stim/assets/48498823/d3ff4b65-3e76-4853-86c8-b1409b22927a)

стало менее удобно

![image](https://github.com/rusefi/stim/assets/48498823/75abdfc5-ce2f-4b9f-88e0-98268b70182d)

**Comment by Qwerty-OFF** [comment]
![image](https://github.com/rusefi/stim/assets/4116383/a828a90a-d58b-4cab-a8da-ca919018711e)
