### ISSUE TITLE
document USB pins on schematics

### ISSUE THREAD

**Issue by rusefillc** [rusefi/stim#29]
we rely on nucleo USB connectivity let's mention this on the schematics. See also https://github.com/rusefi/stim/issues/28

```
#define EFI_USB_SERIAL_PORT GPIOA
#define EFI_USB_SERIAL_PIN_DM 11
#define EFI_USB_SERIAL_PIN_DP 12
```

**Comment by Nadezhda-n** [comment]
![image](https://github.com/rusefi/stim/assets/99179773/d3ebf51a-953c-4fc9-80d5-36851ef25838)

**Comment by Qwerty-OFF** [comment]
![image](https://github.com/rusefi/stim/assets/4116383/28ec880c-7c44-4b87-98f7-ce12e5569b55)
