### ISSUE TITLE
Hall sensor / digital switch stim

### ISSUE THREAD

**Issue by rusefillc** [rusefi/stim#3]
we need up to eight channels of Hall / switch stimulation

**Comment by stefanst** [comment]
Hall should be easy- just an NPN transistor.

**Comment by rusefillc** [comment]
but we need 16 of these so some muxing?

**Comment by stefanst** [comment]
If memory serves right, more like de-muxing. But yes.

**Comment by mck1117** [comment]
or not - just use a 208 pin mcu

**Comment by rusefillc** [comment]
208 pin MCU does not exist in 2021.
only 144 pin MCU exist unless you give me available part numbers for Nucleo 176 or else :)

**Comment by rusefillc** [comment]
firmware side https://github.com/rusefi/rusefi-hardware/issues/222

next step: selecting eight pins on 144 pin STM32 Nucleo-F429ZI which we can toggle without any interference from other hardware on STM32 Nucleo-F429ZI and not yet used by existing https://github.com/rusefi/rusefi-hardware/tree/main/digital-inputs

**Comment by rusefillc** [comment]
CN1-2 would be most convenient
CN1-1 second most convenient

но можно любые

![photo_2023-07-26_15-15-01](https://github.com/rusefi/stim/assets/48498823/c35347ae-b751-4f72-a8ef-aea657a89ee8)

**Comment by andreika-git** [comment]
Let's use these 8 pins on the CN12 connector:

![зображення](https://github.com/rusefi/stim/assets/15104768/0d0ddc86-098c-474d-be37-980702c782da)

PE0, PE7-13.
They are not used for any specific purposes, and have inessential alternative functions: UART7, UART8, SPI4. Also some of them have PWM if needed.

**Comment by rusefillc** [comment]
@Qwerty-OFF сделай пожалуйста схематику одного вывода для тестирования цифрового датчика на пине PE0?

**Comment by Qwerty-OFF** [comment]
Сделал
![image](https://github.com/rusefi/stim/assets/4116383/6949aa0e-215a-4046-97e5-d8d8c0581257)

**Comment by Nadezhda-n** [comment]
![image](https://github.com/rusefi/stim/assets/99179773/227e7f8c-664f-4bf3-8d4b-c6d6eaaa66bc)
OUT_HALO_* на 6437288-3?

**Comment by rusefillc** [comment]
@Nadezhda-n https://rusefi.com/docs/pinouts/stim/?connector=main&pin=15B и так далее, что digital out - не только hall

**Comment by Nadezhda-n** [comment]
> @Nadezhda-n https://rusefi.com/docs/pinouts/stim/?connector=main&pin=15B и так далее, что digital out - не только hall

что
https://github.com/rusefi/stim/issues/14#issuecomment-1531423645
Не помню как это взялось уже, но это мимо, получается?

**Comment by Nadezhda-n** [comment]
Есть 4 out на NUCLEO-F429ZI
А на разъеме 8 digital out
@rusefillc 

>>
![image](https://github.com/rusefi/stim/assets/99179773/c4a7e3d2-31f7-48c2-a137-7bfcbae6b989)

**Comment by Nadezhda-n** [comment]
Теперь я понимаю, что digital out как раз для этих hallo
