### ISSUE TITLE
CAN should use PD0 & PD1

### ISSUE THREAD

**Issue by rusefillc** [rusefi/stim#30]
печаль
```
#define EFI_USB_SERIAL_PORT GPIOA
#define EFI_USB_SERIAL_PIN_DM 11
#define EFI_USB_SERIAL_PIN_DP 12
```

```
#define CAN_PORT GPIOA
#define CAN_PIN_RX 11
#define CAN_PIN_TX 12
```

**Comment by rusefillc** [comment]
попробую перерезать CAN_TX CAN_RX и кину сопли на

![image](https://github.com/rusefi/stim/assets/48498823/dcbd6737-9406-43c8-9db3-116b82a37328)

**Comment by rusefillc** [comment]
на схеме CN11 снизу обрезаны/не являются часть CN11 два GND пина

для уточнения: вот эти запаянные пины используем для CAN шины теперь

![WhatsApp Image 2023-08-20 at 21 07 52](https://github.com/rusefi/stim/assets/48498823/bf4cc304-dd35-4049-975b-26964b17a33f)

**Comment by Nadezhda-n** [comment]
> на схеме CN11 снизу обрезаны два GND пина, для уточнения вот эти пины используем для CAN шины теперь
> 
> ![WhatsApp Image 2023-08-20 at 21 07 52](https://user-images.githubusercontent.com/48498823/261888297-bf4cc304-dd35-4049-975b-26964b17a33f.jpg)

Сюда добавить??
![image](https://github.com/rusefi/stim/assets/99179773/02429015-6fad-4f6d-95dd-d54eadd8bc2a)

Не совсем понятно, на самом деле

**Comment by rusefillc** [comment]
там возможно эти пины два раза выведены - ты смотришь на CN9

я как-то так получилось использовал другие на CN11, давай уже для простоты используем их

https://os.mbed.com/platforms/ST-Nucleo-F429ZI/

![image](https://github.com/rusefi/stim/assets/48498823/7c1c3c4c-1b05-4545-b808-4160e4073e71)

![image](https://github.com/rusefi/stim/assets/48498823/aef14f63-ff46-4521-8dce-e13c06d187f5)

**Comment by Nadezhda-n** [comment]
> попробую перерезать CAN_TX CAN_RX и кину сопли на
> 
> ![image](https://user-images.githubusercontent.com/48498823/261830868-dcbd6737-9406-43c8-9db3-116b82a37328.png)

Резать еще что-то надо? 
Или дублируем выводы просто?

**Comment by rusefillc** [comment]
на плате 0.2 я отрезал старые CAN трассы

на rev C трассы будут вести только на PD0/PD1 и не будет CAN трасс на PA10/PA11

**Comment by Nadezhda-n** [comment]
оки
![image](https://github.com/rusefi/stim/assets/99179773/22c985b4-3fae-4d3a-afc0-26d1bf85cafe)

**Comment by Qwerty-OFF** [comment]
![image](https://github.com/rusefi/stim/assets/4116383/51b8845d-778c-4432-a936-8d2520e51bab)
