### ISSUE TITLE
LEDs for +5v inputs

### ISSUE THREAD

**Issue by rusefillc** [rusefi/stim#33]
we should have two red LEDs for the two +5v inputs

https://rusefi.com/docs/pinouts/stim/?connector=main&pin=1B
https://rusefi.com/docs/pinouts/stim/?connector=main&pin=2B

**Comment by Nadezhda-n** [comment]
![image](https://github.com/rusefi/stim/assets/99179773/3afc8986-f9ac-4edf-8b90-0fe442e844a2)
не уверенна насчет номиналов, по аналогии на маленький ток сделала

**Comment by Nadezhda-n** [comment]
![image](https://github.com/rusefi/stim/assets/99179773/006d3881-d8a3-4007-b86b-4b26efda3d56)
