### ISSUE TITLE
second CAN bus

### ISSUE THREAD

**Issue by rusefillc** [rusefi/stim#35]
на нуклео наверняка есть вторая КАН шина? можно нам её тоже на неиспользуемые пины superseal?

**Comment by Qwerty-OFF** [comment]
PB6/PB12. OUT0 перемещен с PB12 на PD8.
Установить чип CAN и вывести CAN на via?

![image](https://github.com/rusefi/stim/assets/4116383/6692d84e-5d46-462b-8b83-de75f1cf846d)

**Comment by rusefillc** [comment]
> Установить чип CAN 

да

> вывести CAN на via?

пока да, у нас там есть via на разъёме - но мы пока не будет на разъём

**Comment by Qwerty-OFF** [comment]
![image](https://github.com/rusefi/stim/assets/4116383/682bae89-1b13-4eb8-9bb5-ceba34d0d0a6)

**Comment by rusefillc** [comment]
>  OUT0 перемещен с PB12 на PD8.

жутко извиняюсь, но хочется уточнить: это единственное изменение распиновки и несовместимость между ревизиями A и С?

**Comment by Qwerty-OFF** [comment]
Кажется больше ничего не трогали. Есть вероятность путаницы номеров CAN1/CAN2, если ты пытаешься запустить оба сразу
