### ISSUE TITLE
push button to reset +12v power

### ISSUE THREAD

**Issue by rusefillc** [rusefi/stim#37]
asking for normal-connect, push-disconnect push button to reset +12v power line

**Comment by Qwerty-OFF** [comment]
![image](https://github.com/rusefi/stim/assets/4116383/fdb927f1-f794-4068-a6e1-cd8d300d8981)

**Comment by rusefillc** [comment]
@Qwerty-OFF как сложно, а нельзя вот просто кнопкой? или ток слишком большой?

**Comment by Qwerty-OFF** [comment]
Нормально замкнутая кнопка это экзотика. Могу поставить переключатель on/off

**Comment by rusefillc** [comment]
@Qwerty-OFF согласен на on/off

**Comment by Qwerty-OFF** [comment]
![image](https://github.com/rusefi/stim/assets/4116383/db3c7a59-41b3-465d-86a4-16dcc29fb541)
