### ISSUE TITLE
vias for NC pins

### ISSUE THREAD

**Issue by rusefillc** [rusefi/stim#39]
prototyping via so much better than NC pin

![image](https://github.com/rusefi/stim/assets/48498823/666e4086-7bb7-4547-847a-79a02e4944ae)

**Comment by rusefillc** [comment]
все пины может не нужно, ну хоть 8 штук бы в сумме

![image](https://github.com/rusefi/stim/assets/48498823/170d3807-316a-4dd0-b344-bf2d31a44e1a)

**Comment by Nadezhda-n** [comment]
Да не жалко
![image](https://github.com/rusefi/stim/assets/99179773/5e901d1a-57c3-45fc-9a6d-8eb45c91ae6b) 
![image](https://github.com/rusefi/stim/assets/99179773/7e2648e5-1ab7-44bd-b13d-7bc7f518c21b)

![image](https://github.com/rusefi/stim/assets/99179773/372f566e-0473-473e-8330-ad51b45d924f)
