### ISSUE TITLE
Analog Sensing Board

### ISSUE THREAD

**Issue by rusefillc** [rusefi/stim#4]
we need 3v SPI chainable 16 channel 5v ADC board
could be any number of chips but lower is better to reduce CS lines?

**Comment by rusefillc** [comment]
board should have optional pull-ups/pull-downs allowing low side drive sensing, i.e. testing of injector drivers etc

**Comment by mck1117** [comment]
Another option is to use analog switches/muxes and use onboard STM ADC.  One ADC gets us 16 channels, and a bunch of 2x or 4x muxes would get 32 or 64 channels.

**Comment by rusefillc** [comment]
But do we even need ADC at all?

#6
