### ISSUE TITLE
rev C вся нуклео не включается от 12 вольт

### ISSUE THREAD

**Issue by rusefillc** [rusefi/stim#45]
на rev C есть кнопка

при питании от 12 вольт в одном положении ничего не светится

при питании от 12 вольт в другом положении мигает LD4 наверху нуклео, но на основном блоке нуклео ничего не светится

прошивка stim начинает мигать голубым только при подключении microUSB

**Comment by Qwerty-OFF** [comment]
![image](https://github.com/user-attachments/assets/bda4547f-21ee-4576-bbec-3cc02db3fc0f)
Джампер сюда. Питание 12В максимум

**Comment by Qwerty-OFF** [comment]
Мы будем использовать E5V
![image](https://github.com/user-attachments/assets/234e77ef-1893-417a-96de-2aa99b133b52)

**Comment by Qwerty-OFF** [comment]
Поставил стабилизатор на 5В

**Comment by rusefillc** [comment]
extra nucleo pin for 5v


![WhatsApp Image 2024-10-31 at 16 53 24_8006fc7c](https://github.com/user-attachments/assets/bc9c9a6f-6f5e-4674-ae58-bf9b462fb367)

**Comment by rusefillc** [comment]
JP3 подвинул, как на картинке

третий пин J20 припаял, как на картинке

LD4 мигает
LD6 не горит, прошивка не стартует @Qwerty-OFF

**Comment by Qwerty-OFF** [comment]
JP3 передвинь в E5V, та картинка была для внешних 12В без стабилизатора
