### ISSUE TITLE
rev C реальный мир мешает проводам

### ISSUE THREAD

**Issue by rusefillc** [rusefi/stim#46]
огромный переключатель не даёт возможности воткнуть нижний провод, нужно двигать на 12мм влево

![WhatsApp Image 2024-10-18 at 10 32 54_a87667ea](https://github.com/user-attachments/assets/debf5413-308a-4ed0-9627-50a18a098e80)

**Comment by Qwerty-OFF** [comment]
![image](https://github.com/user-attachments/assets/d1c31834-4924-4e20-95f0-c656cee2ac26)
