### ISSUE TITLE
just damaged rev C number 2 while playing with 10R 20W between 19C and 20C

### ISSUE THREAD

**Issue by rusefillc** [rusefi/stim#48]
we were trying to add real load to improve detection of bad ECUs

specific board was passing good with 0.58v MAP as expected using 8B ``Reference voltage out 2 (MAP) 0.6v``

suddenly voltage check started to fail

```
 * BAD channel 4 (MAP): voltage 0.363921568 (raw 32) not in range (0.670109504..0.000000000)
 ***********************************************
 ***********************************************
 * BAD channel 4 (MAP): voltage 0.363921568 (raw 32) not in range (0.670109504..0.000000000)
 ***********************************************
 ***********************************************
 * BAD channel 4 (MAP): voltage 0.363921568 (raw 32) not in range (0.670109504..0.000000000)
```

![WhatsApp Image 2024-10-25 at 22 31 18_894ff7be](https://github.com/user-attachments/assets/983a9e7b-fe87-4ef3-a4a0-9a139b315558)

**Comment by jharvey** [comment]
@rusefillc @Qwerty-OFF 
While TC4427 can drive around 1.5A, the MUX CD4067BM96 is only rated for around +/- 20mA. With a recommended max of +/- 10ma continuous. It appears the MUX is not protected against overcurrent, so its possible the 10R damaged that channel of the MUX, perhaps other channels as well. However R1 the 1.2k should limit the current to 10mA. So it should be OK.

**Comment by rusefillc** [comment]
my bad that was a software issue
