### ISSUE TITLE
Basics

### ISSUE THREAD

**Issue by stefanst** [rusefi/stim#5]
Before we start designing circuits, how about a list of requirements?

**Comment by rusefillc** [comment]
https://github.com/rusefi/rusefi/wiki/dev-hardware-quality-control#requirements

**Comment by rusefillc** [comment]
An interesting thing to approximate would be rate of testing

As is I have no idea what's the time to SEND+ACK a text command via our protocol, and it could be that we would be sending commands to two different devices etc etc.

maybe can between ECU and Stim is really important, that case PC sends Stim one command and Stim exchanges data with ECU directly

**Comment by stefanst** [comment]
I don't see rate of test as a real issue 
Let's say we have a max. of 120 i/o which seems reasonable. Even if each test takes one full second, it would only be 2 minutes total. Setup time with flashing firmware twice (before and after testing) will take longer than that. So the time bottleneck would be setup time.

**Comment by stefanst** [comment]
Most basic configuration:
- 16x digital potentiometer (different values might be helpful)
- 16 digital out for emulating
  - Cam/ Crank sensors
  - Frequency-based sensors
  - switches
- One fake VR output
- 32 digital in for monitoring digital or PWM outputs
- Maybe 8 PWM -> voltage converters (RC) for simple monitoring of PWM outputs?
