### ISSUE TITLE
Digital Outputs Sense

### ISSUE THREAD

**Issue by rusefillc** [rusefi/stim#6]
Open question if low/high/H outputs should be verified using ADC or just digitally

since we need at least 32-48 channels it has to a multiplexor setup

maybe three of same PCB for 16 channels each?

**Comment by rusefillc** [comment]
H-bridge would have what static pull-up/pull-down? or shall we mux pull-ups/pull-downs?

**Comment by rusefillc** [comment]
@andreika-git proposal

![image](https://user-images.githubusercontent.com/15104768/125169915-1013df00-e1b5-11eb-829c-613e75ca2184.png)

in order to distinguish three output states we need De-Mux2 resistor mux

For each of the inputs, we switch MUX1 & DEMUX2 to it and get 4 values:
1) set ECU output to "0" & send "0" to DEMUX2 and get the value from MUX1 = V00
1) set ECU output to "0" & send "1" to DEMUX2 and get the value from MUX1 = V01
1) set ECU output to "1" & send "0" to DEMUX2 and get the value from MUX1 = V10
1) set ECU output to "1" & send "1" to DEMUX2 and get the value from MUX1 = V11
We get 16 possible states which mean:
---
| V00 | V01 | V10 | V11 | Meaning |
|---|---|---|---|---|
| 0 | 0 | 0 | 0 | pin is shorted to GND |
| 0 | 0 | 0 | 1 | ? |
| 0 | 0 | 1 | 0 | ? |
| 0 | 0 | 1 | 1 | pin is normal push-pull output (ignition, dc motor) |
| 0 | 1 | 0 | 0 | pin is normal low-side output |
| 0 | 1 | 0 | 1 | pin is floating |
| 0 | 1 | 1 | 0 | ? |
| 0 | 1 | 1 | 1 | pin is normal high-side output |
| 1 | 0 | 0 | 0 | ? |
| 1 | 0 | 0 | 1 | ? |
| 1 | 0 | 1 | 0 | ? |
| 1 | 0 | 1 | 1 | ? |
| 1 | 1 | 0 | 0 | pin is inverted push-pull output? |
| 1 | 1 | 0 | 1 | pin is inverted low-side output? |
| 1 | 1 | 1 | 0 | ? |
| 1 | 1 | 1 | 1 | pin is shorted to +V |
---


injector scenario: only static resistor is needed maybe not use mux2 here? mux 2 pulls wire up to +3v
12v tach signal scenario: mux2 pulls down. mux1 is responsible for converting +12v input into 3/5v output

H-bridge is really the only one requiring

**Comment by andreika-git** [comment]
MUX1 is something like CD4067BM96_C6525 (16ch_analog_mux) + PCA9538PWR_C201530 (I2C) + opamp + resistor divider + nucleo_analog_input
DEMUX2 is something like 74HC4067PW-118_C179326 (16ch_digital_demux) + 9V power supply (from L7809CV?) + 1-channel-cmos-level-shifter-from-3.3v? + PCA9538PWR_C201530 (I2C)
Of course I2c port expander would be common for all mux/demux/analog etc.

**Comment by rusefillc** [comment]
This all works now!
